In [1]:
import numpy as np
import time

arrA = np.random.randint(1, 100, size=(1000, 1000))
arrB = arrA.copy()

start_time_loop = time.time()
for i in range(1000):
    for j in range(1000):
        arrA[i, j] += 1
end_time_loop = time.time()
print("Time taken:", end_time_loop - start_time_loop, "seconds")

start_time_numpy = time.time()
arrB += 1
end_time_numpy = time.time()
print("Time taken:", end_time_numpy - start_time_numpy, "seconds")

print("Are the two arrays equal?", np.array_equal(arrA, arrB))

Time taken: 0.15279769897460938 seconds
Time taken: 0.0006740093231201172 seconds
Are the two arrays equal? True


# UFuncs

In [2]:
mat = np.random.randint(1, 10, size=(4, 4))
print(mat)
print(mat % 2)

[[1 6 3 4]
 [8 6 8 5]
 [5 5 7 9]
 [2 5 1 7]]
[[1 0 1 0]
 [0 0 0 1]
 [1 1 1 1]
 [0 1 1 1]]


In [3]:
mat2 = np.random.randint(1, 10, size=(4, 4))
print(mat, mat2, mat + mat2, sep="\n\n")

[[1 6 3 4]
 [8 6 8 5]
 [5 5 7 9]
 [2 5 1 7]]

[[7 1 2 9]
 [6 1 1 2]
 [3 9 5 3]
 [6 4 3 2]]

[[ 8  7  5 13]
 [14  7  9  7]
 [ 8 14 12 12]
 [ 8  9  4  9]]


In [4]:
mat = np.random.randint(-6, 10, size=(3, 3))
print(mat)
print(3 * mat - 1)
print(np.abs(mat))


[[-6 -5 -1]
 [ 9 -5  2]
 [ 5  3  9]]
[[-19 -16  -4]
 [ 26 -16   5]
 [ 14   8  26]]
[[6 5 1]
 [9 5 2]
 [5 3 9]]


In [5]:
mat = np.random.randint(1, 100, size=(3, 3))
print(mat, "\n")
print("sin", np.sin(mat), "\n")
print("cos", np.cos(mat))

[[32 82 19]
 [66 63 39]
 [82 46 22]] 

sin [[ 0.55142668  0.31322878  0.14987721]
 [-0.02655115  0.1673557   0.96379539]
 [ 0.31322878  0.90178835 -0.00885131]] 

cos [[ 0.83422336  0.9496777   0.98870462]
 [-0.99964746  0.98589658  0.26664293]
 [ 0.9496777  -0.43217794 -0.99996083]]


In [6]:
mat = np.random.randint(1, 10, size=(3, 3))
print(mat, "\n")
print("exp", np.exp(mat), "\n")
print("log", np.log(mat), "\n")
print("exp - 1", np.expm1(mat), "\n")
print("log1p", np.log1p(mat), "\n")

[[3 1 5]
 [5 3 1]
 [7 3 6]] 

exp [[  20.08553692    2.71828183  148.4131591 ]
 [ 148.4131591    20.08553692    2.71828183]
 [1096.63315843   20.08553692  403.42879349]] 

log [[1.09861229 0.         1.60943791]
 [1.60943791 1.09861229 0.        ]
 [1.94591015 1.09861229 1.79175947]] 

exp - 1 [[  19.08553692    1.71828183  147.4131591 ]
 [ 147.4131591    19.08553692    1.71828183]
 [1095.63315843   19.08553692  402.42879349]] 

log1p [[1.38629436 0.69314718 1.79175947]
 [1.79175947 1.38629436 0.69314718]
 [2.07944154 1.38629436 1.94591015]] 



In [7]:
from scipy import special

mat = np.random.randint(1, 10, size=(3, 3))
print("erf", special.erf(mat))

erf [[0.84270079 1.         0.99532227]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]


In [8]:
source = np.arange(16).reshape(4, 4)
dest = np.empty_like(source)
np.add(source, 10, out=dest)
print(dest)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [9]:
mat = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.add.reduce(mat))

45


In [10]:
arr = np.arange(1, 10)
np.add.outer(arr, arr)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])