In [37]:
import numpy as np
import time

arrA = np.random.randint(1, 100, size=(1000, 1000))
arrB = arrA.copy()

start_time_loop = time.time()
for i in range(1000):
    for j in range(1000):
        arrA[i, j] += 1
end_time_loop = time.time()
print("Time taken:", end_time_loop - start_time_loop, "seconds")

start_time_numpy = time.time()
arrB += 1
end_time_numpy = time.time()
print("Time taken:", end_time_numpy - start_time_numpy, "seconds")

print("Are the two arrays equal?", np.array_equal(arrA, arrB))

Time taken: 0.17553496360778809 seconds
Time taken: 0.0006597042083740234 seconds
Are the two arrays equal? True


# UFuncs

In [38]:
mat = np.random.randint(1, 10, size=(4, 4))
print(mat)
print(mat % 2)

[[8 6 5 7]
 [4 8 3 4]
 [3 6 9 4]
 [7 6 2 8]]
[[0 0 1 1]
 [0 0 1 0]
 [1 0 1 0]
 [1 0 0 0]]


In [39]:
mat2 = np.random.randint(1, 10, size=(4, 4))
print(mat, mat2, mat + mat2, sep="\n\n")

[[8 6 5 7]
 [4 8 3 4]
 [3 6 9 4]
 [7 6 2 8]]

[[5 7 8 9]
 [3 2 4 5]
 [4 3 5 6]
 [2 2 7 2]]

[[13 13 13 16]
 [ 7 10  7  9]
 [ 7  9 14 10]
 [ 9  8  9 10]]


In [41]:
mat = np.random.randint(1, 10, size=(3, 3))
print(mat)
print(3 * mat - 1)

[[6 7 4]
 [8 6 4]
 [3 8 4]]
[[17 20 11]
 [23 17 11]
 [ 8 23 11]]


In [43]:
mat = np.random.randint(1, 100, size=(3, 3))
print(mat, "\n")
print("sin", np.sin(mat), "\n")
print("cos", np.cos(mat))

[[ 9 86 95]
 [66 51 94]
 [25 28 40]] 

sin [[ 0.41211849 -0.92345845  0.68326171]
 [-0.02655115  0.67022918 -0.24525199]
 [-0.13235175  0.27090579  0.74511316]] 

cos [[-0.91113026 -0.38369844  0.73017356]
 [-0.99964746  0.7421542   0.96945937]
 [ 0.99120281 -0.96260587 -0.66693806]]


In [ ]:
mat = np.random.randint(1, 10, size=(3, 3))
print(mat, "\n")
print("exp", np.exp(mat), "\n")
print("log", np.log(mat), "\n")
print("exp - 1", np.expm1(mat), "\n")
print("log1p", np.log1p(mat), "\n")

[[7 1 1]
 [9 3 6]
 [3 6 3]] 

exp [[1.09663316e+03 2.71828183e+00 2.71828183e+00]
 [8.10308393e+03 2.00855369e+01 4.03428793e+02]
 [2.00855369e+01 4.03428793e+02 2.00855369e+01]] 

log [[1.94591015 0.         0.        ]
 [2.19722458 1.09861229 1.79175947]
 [1.09861229 1.79175947 1.09861229]] 

exp - 1 [[1.09563316e+03 1.71828183e+00 1.71828183e+00]
 [8.10208393e+03 1.90855369e+01 4.02428793e+02]
 [1.90855369e+01 4.02428793e+02 1.90855369e+01]] 

log1p [[2.07944154 0.69314718 0.69314718]
 [2.30258509 1.38629436 1.94591015]
 [1.38629436 1.94591015 1.38629436]] 



In [51]:
from scipy import special

mat = np.random.randint(1, 10, size=(3, 3))
print("erf", special.erf(mat))

erf [[1.         1.         0.99999998]
 [1.         1.         1.        ]
 [0.99532227 1.         0.84270079]]


In [54]:
source = np.arange(16).reshape(4, 4)
dest = np.empty_like(source)
np.add(source, 10, out=dest)
print(dest)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [57]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.add.reduce(mat))
print(np.add.accumulate(mat, axis=0))

[12 15 18]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [58]:
arr = np.arange(1, 10)
np.add.outer(arr, arr)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])