In [16]:
import numpy as np

In [17]:
mat = np.array([[1, 2], [3, 4]])
print("inverse", np.linalg.inv(mat), sep="\n")

inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
mat = np.random.randint(1, 10, size=(9, 9))
print("determinant", np.linalg.det(mat), sep="\n")

determinant
1957144.0000000028


In [19]:
mat = np.array([[1, 2], [3, 4]])
print("transpose", np.transpose(mat), sep="\n")

transpose
[[1 3]
 [2 4]]


In [21]:
mat = np.random.randint(1, 10, size=(6, 6))
b = np.random.randint(1, 10, size=6)
x = np.linalg.solve(mat, b)
print("mat", mat, sep="\n")
print("b", b, sep="\n")
print("solution", x, sep="\n")


mat
[[5 7 1 5 3 2]
 [5 4 1 2 2 6]
 [4 3 1 8 2 1]
 [9 8 3 9 3 4]
 [5 8 9 2 7 9]
 [3 3 8 9 6 5]]
b
[4 5 2 8 3 4]
solution
[-57.60986547  43.7309417   10.88789238  25.34080717 -73.07623318
  33.78475336]
