In [2]:
import numpy as np

In [3]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [17]:
import time

arr = np.random.randn(5_000)
start_time = time.time()
bubble_sort(arr.copy())
end_time = time.time()
print("Time taken to sort the array with bubble sort:", end_time - start_time, "seconds")

start_time = time.time()
np.sort(arr.copy())
end_time = time.time()
print("Time taken to sort the array with NumPy's sort:", end_time - start_time, "seconds")

Time taken to sort the array with bubble sort: 1.6163594722747803 seconds
Time taken to sort the array with NumPy's sort: 0.00026917457580566406 seconds


In [18]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_indices = np.argsort(arr)
print("Original array:", arr)
print("Indices that would sort the array:", sorted_indices)

Original array: [3 1 4 1 5 9 2 6 5]
Indices that would sort the array: [1 3 6 0 2 4 8 7 5]


In [20]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Original array:\n", arr)
sorted_arr = np.sort(arr, axis=0)
print("Array sorted along the first axis (columns):\n", sorted_arr)
sorted_arr = np.sort(arr, axis=1)
print("Array sorted along the last axis (rows):\n", sorted_arr)


Original array:
 [[95 75 67 52 79]
 [ 4 27 51 41 93]
 [30 54 35 73 51]
 [28 48 96 56 61]
 [46 18  7 88 15]]
Array sorted along the first axis (columns):
 [[ 4 18  7 41 15]
 [28 27 35 52 51]
 [30 48 51 56 61]
 [46 54 67 73 79]
 [95 75 96 88 93]]
Array sorted along the last axis (rows):
 [[52 67 75 79 95]
 [ 4 27 41 51 93]
 [30 35 51 54 73]
 [28 48 56 61 96]
 [ 7 15 18 46 88]]


In [21]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print(np.partition(arr, 4))

[1 1 2 3 4 5 5 6 9]
