In [42]:
import numpy as np

In [43]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [44]:
import time

arr = np.random.randn(5_000)
arr_copy = arr.copy()
start_time = time.time()
bubble_sort(arr)
end_time = time.time()
print("Time taken to sort the array with bubble sort:", end_time - start_time, "seconds")

start_time = time.time()
np.sort(arr_copy)
end_time = time.time()
print("Time taken to sort the array with NumPy's sort:", end_time - start_time, "seconds")

KeyboardInterrupt: 

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_indices = np.argsort(arr)
print("Original array:", arr)
print("Indices that would sort the array:", sorted_indices)

Original array: [3 1 4 1 5 9 2 6 5]
Indices that would sort the array: [1 3 6 0 2 4 8 7 5]


In [ ]:
arr = np.random.randint(1, 100, size=(5, 5))
print("Original array:\n", arr)
sorted_arr = np.sort(arr, axis=0)
print("Array sorted along the first axis (columns):\n", sorted_arr)
sorted_arr = np.sort(arr, axis=1)
print("Array sorted along the last axis (rows):\n", sorted_arr)


Original array:
 [[51 22 21 88 53]
 [66 29 61 87 58]
 [ 5 37  6 19 58]
 [49 89 96 12 42]
 [79 51 93 85 52]]
Array sorted along the first axis (columns):
 [[ 5 22  6 12 42]
 [49 29 21 19 52]
 [51 37 61 85 53]
 [66 51 93 87 58]
 [79 89 96 88 58]]
Array sorted along the last axis (rows):
 [[21 22 51 53 88]
 [29 58 61 66 87]
 [ 5  6 19 37 58]
 [12 42 49 89 96]
 [51 52 79 85 93]]


In [66]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([1, 2, 3, 4, 5, 6, 7])