# NumPy Array Attributes

In [55]:
import numpy as np
mat = np.random.randint(1, 100, size=(4, 4))
mat

array([[25, 79, 87, 16],
       [57, 71, 70,  3],
       [93,  8, 67, 50],
       [42, 94, 62, 93]], dtype=int32)

In [56]:
print("ndim:", mat.ndim)
print("shape:", mat.shape)
print("size:", mat.size)
print("dtype:", mat.dtype)
print("itemsize:", mat.itemsize)
print("nbytes:", mat.nbytes)

ndim: 2
shape: (4, 4)
size: 16
dtype: int32
itemsize: 4
nbytes: 64


In [57]:
print(mat, end="\n\n")
print(mat[0], end="\n\n")
print(mat[-2], end="\n\n")

[[25 79 87 16]
 [57 71 70  3]
 [93  8 67 50]
 [42 94 62 93]]

[25 79 87 16]

[93  8 67 50]



In [58]:
print(mat, end="\n\n")
print(mat[0,1], end="\n\n")
print(mat[1:3, 2:3], end="\n\n")
print(mat[2:4], end="\n\n")
print(mat[::2, ::2], end="\n\n")

[[25 79 87 16]
 [57 71 70  3]
 [93  8 67 50]
 [42 94 62 93]]

79

[[70]
 [67]]

[[93  8 67 50]
 [42 94 62 93]]

[[25 87]
 [93 67]]



In [59]:
print(mat[:, 1], end="\n\n")
print(mat[1, :], end="\n\n")

[79 71  8 94]

[57 71 70  3]



In [60]:
print(mat, end="\n\n")
submat = mat[1:3, 1:3]
submat[:] = 999
print(mat, end="\n\n")

[[25 79 87 16]
 [57 71 70  3]
 [93  8 67 50]
 [42 94 62 93]]

[[ 25  79  87  16]
 [ 57 999 999   3]
 [ 93 999 999  50]
 [ 42  94  62  93]]



In [62]:
mat_copy = mat.copy()
mat_copy[0, :] = 111
print(mat, end="\n\n")

[[ 25  79  87  16]
 [ 57 999 999   3]
 [ 93 999 999  50]
 [ 42  94  62  93]]



In [ ]:
mat2 = np.arange(1, 17).reshape(3, 4)
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])