# NumPy Array Attributes

In [98]:
import numpy as np
mat = np.random.randint(1, 100, size=(4, 4))
mat

array([[97, 64, 66, 54],
       [67, 72, 89, 40],
       [59, 41, 53, 83],
       [75, 74, 65, 87]], dtype=int32)

In [99]:
print("ndim:", mat.ndim)
print("shape:", mat.shape)
print("size:", mat.size)
print("dtype:", mat.dtype)
print("itemsize:", mat.itemsize)
print("nbytes:", mat.nbytes)

ndim: 2
shape: (4, 4)
size: 16
dtype: int32
itemsize: 4
nbytes: 64


In [100]:
print(mat, end="\n\n")
print(mat[0], end="\n\n")
print(mat[-2], end="\n\n")

[[97 64 66 54]
 [67 72 89 40]
 [59 41 53 83]
 [75 74 65 87]]

[97 64 66 54]

[59 41 53 83]



In [101]:
print(mat, end="\n\n")
print(mat[0,1], end="\n\n")
print(mat[1:3, 2:3], end="\n\n")
print(mat[2:4], end="\n\n")
print(mat[::2, ::2], end="\n\n")

[[97 64 66 54]
 [67 72 89 40]
 [59 41 53 83]
 [75 74 65 87]]

64

[[89]
 [53]]

[[59 41 53 83]
 [75 74 65 87]]

[[97 66]
 [59 53]]



In [102]:
print(mat, end="\n\n")
print(mat[:, 1], end="\n\n")
print(mat[1, :], end="\n\n")

[[97 64 66 54]
 [67 72 89 40]
 [59 41 53 83]
 [75 74 65 87]]

[64 72 41 74]

[67 72 89 40]



In [103]:
print(mat, end="\n\n")
submat = mat[1:3, 1:3]
submat[:] = 999
print(mat, end="\n\n")

[[97 64 66 54]
 [67 72 89 40]
 [59 41 53 83]
 [75 74 65 87]]

[[ 97  64  66  54]
 [ 67 999 999  40]
 [ 59 999 999  83]
 [ 75  74  65  87]]



In [104]:
mat_copy = mat.copy()
mat_copy[0, :] = 111
print(mat, end="\n\n")

[[ 97  64  66  54]
 [ 67 999 999  40]
 [ 59 999 999  83]
 [ 75  74  65  87]]



In [ ]:
mat2 = np.arange(1, 17).reshape(4, 4)
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

: 